In [1]:
import torch.nn as nn
import torch

In [4]:
a = torch.arange(0, 10)

In [5]:
b = a.float()

In [1]:
import networkx as nx
print(type(nx.DiGraph()))

<class 'networkx.classes.digraph.DiGraph'>


In [7]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [9]:
d_model = 100

In [11]:
import math

In [13]:
torch.arange(0, d_model, 2).float() 

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
        28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52., 54.,
        56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76., 78., 80., 82.,
        84., 86., 88., 90., 92., 94., 96., 98.])

In [14]:
math.log(10000.0) / d_model

0.09210340371976183

In [15]:
math.log(10000.0)

9.210340371976184

In [12]:
(torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

tensor([1.0000e+00, 8.3176e-01, 6.9183e-01, 5.7544e-01, 4.7863e-01, 3.9811e-01,
        3.3113e-01, 2.7542e-01, 2.2909e-01, 1.9055e-01, 1.5849e-01, 1.3183e-01,
        1.0965e-01, 9.1201e-02, 7.5858e-02, 6.3096e-02, 5.2481e-02, 4.3652e-02,
        3.6308e-02, 3.0200e-02, 2.5119e-02, 2.0893e-02, 1.7378e-02, 1.4454e-02,
        1.2023e-02, 1.0000e-02, 8.3176e-03, 6.9183e-03, 5.7544e-03, 4.7863e-03,
        3.9811e-03, 3.3113e-03, 2.7542e-03, 2.2909e-03, 1.9055e-03, 1.5849e-03,
        1.3183e-03, 1.0965e-03, 9.1201e-04, 7.5858e-04, 6.3096e-04, 5.2481e-04,
        4.3652e-04, 3.6308e-04, 3.0200e-04, 2.5119e-04, 2.0893e-04, 1.7378e-04,
        1.4454e-04, 1.2023e-04])

In [16]:
a = torch.tensor([1,3,4,5])
b = torch.tensor([1,3,4,5])
a+b

tensor([ 2,  6,  8, 10])

In [18]:
a=torch.zeros(1,2,3,4)


In [21]:
a.transpose(1, 2).contiguous().shape

torch.Size([1, 3, 2, 4])

In [22]:
nn.Parameter(torch.ones(5))

Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [26]:
import torch.nn as nn
import torch

class LayerNorm(nn.Module):
    "Construct a layernorm module (See citation for details)."

    def __init__(self, features, eps=1e-6):
        super(LayerNorm, self).__init__()
        self.a_2 = nn.Parameter(torch.ones(features))  # 缩放参数
        self.b_2 = nn.Parameter(torch.zeros(features))  # 平移参数
        self.eps = eps

    def forward(self, x):
        mean = x.mean(-1, keepdim=True)
        std = x.std(-1, keepdim=True)
        # 归一化并应用缩放和平移
        return self.a_2 * (x - mean) / (std + self.eps) + self.b_2
    
normLayer = LayerNorm(10)
arry = torch.tensor([1,2,3,4,5,6,7,8,9,0], dtype=torch.float)
normLayer(arry)

tensor([-1.1560, -0.8257, -0.4954, -0.1651,  0.1651,  0.4954,  0.8257,  1.1560,
         1.4863, -1.4863], grad_fn=<AddBackward0>)

In [27]:
torch.randn(32, 10)

tensor([[ 1.9231e-01, -7.5936e-01,  7.6216e-01, -2.7099e-01,  1.4829e+00,
          1.0880e+00,  2.7063e-01,  1.6318e+00,  1.1484e+00, -4.2952e-01],
        [-2.6317e+00,  3.2529e-01,  1.6173e+00, -8.6755e-01,  3.9775e-01,
          7.4828e-02, -4.3268e-01,  3.9665e-01,  6.2987e-01,  8.4633e-02],
        [-4.1163e-01,  1.4869e+00, -1.2393e+00,  1.6733e+00, -7.8253e-01,
         -3.8222e-01, -8.4614e-01, -4.1525e-02, -1.4361e+00, -7.0270e-01],
        [ 3.5370e-01,  6.7767e-01,  1.1343e+00,  3.4521e-01,  2.8482e-01,
          1.5981e-01, -1.8372e+00, -1.4218e+00, -9.1902e-01,  7.4875e-01],
        [-1.0412e+00, -2.1860e-01,  4.3432e-01,  1.1943e+00,  9.0879e-01,
         -5.1829e-01,  7.0307e-01, -5.2266e-01, -2.5390e+00,  1.7265e-01],
        [ 6.5656e-01, -4.3206e-02, -3.4181e-01, -1.1714e-01,  1.3582e+00,
         -1.6198e-01, -6.5091e-01,  4.1445e-02, -1.6852e+00, -4.4734e-01],
        [ 1.1310e+00, -6.9064e-01, -1.4170e+00, -1.0436e+00,  4.7621e-01,
         -1.2061e-01, -5.5075e-0

如何写一个训练过程：

### 初始化

1.cuda_condition = torch.cuda.is_available() and with_cuda
        self.device = torch.device("cuda:0" if cuda_condition else "cpu")
        选择是否使用cuda
        
2.self.bert = bert
        在每次训练以及初始化时，将模型存储在训练类中
        
3.在外层附加上额外训练用的模型并将模型移动（to）到指定位置
self.model = BERTLM(bert, vocab_size).to(self.device)

这里model和bert的参数是

4.如果可以并行则并行：
        if with_cuda and torch.cuda.device_count() > 1:
            print("Using %d GPUS for BERT" % torch.cuda.device_count())
            self.model = nn.DataParallel(self.model, device_ids=cuda_devices)

5.self.train_data = train_dataloader
  self.test_data = test_dataloader
  存储加载数据的方法
  
6.self.optim = AdamW(self.model.parameters(), lr=lr, betas=betas, weight_decay=weight_decay)
存储优化方法（也可以自己写优化器）  
例如：
self.optim_schedule = ScheduledOptim(self.optim, self.bert.hidden, n_warmup_steps=warmup_steps)


7.
##### 这里还不太懂
建立存储lossfunction：
        self.masked_criterion = nn.NLLLoss(ignore_index=0)
        self.dfg_next_criterion = nn.NLLLoss()
        self.cfg_next_criterion = nn.NLLLoss()
        self.comp_criterion = nn.NLLLoss(ignore_index=0)
        self.sentence_bert = nn.NLLLoss()
        
### 需要包内涵的方法

train：调用iteration（进行一次训练） 传入：轮数 Loader bool值训练

test：调用iteration（进行一次测试） 传入：轮数 Loader bool值不训练

iteration接收：轮数 Loader bool值是否训练



save

In [29]:
import numpy as np
np.power(2,3)

8

In [28]:
torch.cuda.device_count()

1

这个表示法提取的是所有序列的第一个位置的向量。假设 x 的形状是 (batch_size, sequence_length, hidden_size)，那么 x[:, 0] 的形状将是 (batch_size, hidden_size)

    def forward(self, x):  ## 如果猜的没错的话，应该是对bert输入两个句子，判断此两个句子是否相邻，而且开头为
        return self.softmax(self.linear(x[:, 0]))

In [5]:
from torch.utils.data import Dataset, DataLoader
import torch


class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

data = [
    {
        'adj_tensor1': torch.ones(1, 3),
        'attr_tensor1': torch.randn(2, 4),
        'adj_tensor2': torch.randn(2, 3),
        'attr_tensor2': torch.randn(2, 4),
        'label': torch.tensor(1.0, dtype=torch.float32)
    },
    {
        'adj_tensor1': torch.ones(1, 3),
        'attr_tensor1': torch.randn(2, 4),
        'adj_tensor2': torch.randn(2, 3),
        'attr_tensor2': torch.randn(2, 4),
        'label': torch.tensor(0.0, dtype=torch.float32)
    }
]

dataset = CustomDataset(data)

# 使用默认的 collate_fn
dataloader = DataLoader(dataset, batch_size=2)

# 打印批次数据
for batch in dataloader:
    print(batch)

{'adj_tensor1': tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]]), 'attr_tensor1': tensor([[[-0.3199,  0.7037,  1.2735, -0.6171],
         [ 0.3625, -0.8343, -1.3598,  0.2631]],

        [[-0.5888, -0.9932,  0.7368,  1.0732],
         [ 2.1365, -0.4453, -0.8843,  0.6156]]]), 'adj_tensor2': tensor([[[-0.3998,  2.2557, -1.2906],
         [-0.2718,  2.5890, -0.3614]],

        [[-0.4702,  2.1972,  0.1941],
         [ 0.3763, -1.3900, -0.7574]]]), 'attr_tensor2': tensor([[[ 1.5776,  0.7897, -0.1836,  1.7336],
         [ 1.0250,  0.2822, -2.1653, -1.1733]],

        [[ 0.6936, -0.0504, -1.3130, -0.2504],
         [-0.7676,  0.5087,  1.3085, -0.4470]]]), 'label': tensor([1., 0.])}
